version: '3'

services:
  postgresql:
    container_name: 'oauth2id_postgresql'
    image: postgres:14.9-alpine
    ports:
      - '5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  app: &app_base
    container_name: 'oauth2id_app'
    image: ericguo/oauth2id:${IMAGE_VERSION:-main}
    env_file:
      - app.secret.env
      - app.local.env
    links:
      - postgresql
    logging:
      options:
        max-size: '1g'
        max-file: '10'
    volumes:
      - ./data/uploads:/home/app/homeland/public/uploads
      - ./shared/cache/uploads-thumb:/home/app/cache/uploads-thumb
      - ./shared/plugins:/home/app/homeland/plugins
      - ./log:/home/app/log
      - ./tmp/pids:/home/app/pids
      - ./log:/home/app/homeland/log
      - ./tmp:/home/app/homeland/tmp
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    command: /rails/bin/docker-entrypoint
    ports:
      - '7000'

  caddy:
    image: caddy:2-alpine
    container_name: 'oauth2id_caddy'
    restart: unless-stopped
    env_file:
      - app.local.env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./shared/caddy/data:/data
    links:
      - app
    command: caddy run --config /etc/caddy/Caddyfile
